import { Court, PricingRule, MenuCategory, MenuItem, Tournament, SiteSettings, AdminUser } from "@/types";

export const INITIAL_COURTS: Court[] = [
  {
    id: "court_cricket_main",
    sport: "cricket",
    name: "Main Cricket Turf (Pitch & Nets)",
    zoneId: "zone_cricket",
    active: true,
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    description: "3,740 sq ft box cricket turf with high-bounce central pitch, perimeter net enclosures, and 8x 400W LED stadium floodlights.",
    hourlyBaseRate: 1200,
  },
  {
    id: "court_pickleball_1",
    sport: "pickleball",
    name: "Pro Pickleball Court 1",
    zoneId: "zone_pickleball",
    active: true,
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80",
    description: "USAPA regulation 24x52 ft tournament hardcourt with 8-layer cushion acrylic coating and zero-glare lighting.",
    hourlyBaseRate: 800,
  },
  {
    id: "court_badminton_1",
    sport: "badminton",
    name: "Indoor Badminton Court",
    zoneId: "zone_pickleball",
    active: true,
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80",
    description: "BWF certified synthetic court with anti-slip grip and non-marking shoe requirements.",
    hourlyBaseRate: 700,
  },
  {
    id: "court_volleyball_1",
    sport: "volleyball",
    name: "Pixel Volleyball Arena",
    zoneId: "zone_cricket", // Shared surface with cricket ground!
    active: true,
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80",
    description: "Professional turf volleyball court setup with adjustable tension netting. Shares physical turf zone with cricket ground.",
    hourlyBaseRate: 1000,
  },
];

export const INITIAL_PRICING: PricingRule[] = [
  // Cricket
  { id: "pr_cricket_weekday_offpeak", sport: "cricket", dayType: "weekday", window: "offpeak", startTime: "05:00", endTime: "17:00", pricePerHour: 1000 },
  { id: "pr_cricket_weekday_peak", sport: "cricket", dayType: "weekday", window: "peak", startTime: "17:00", endTime: "01:00", pricePerHour: 1300 },
  { id: "pr_cricket_weekend_all", sport: "cricket", dayType: "weekend", window: "peak", startTime: "05:00", endTime: "01:00", pricePerHour: 1500 },

  // Pickleball
  { id: "pr_pickle_weekday_offpeak", sport: "pickleball", dayType: "weekday", window: "offpeak", startTime: "05:00", endTime: "17:00", pricePerHour: 600 },
  { id: "pr_pickle_weekday_peak", sport: "pickleball", dayType: "weekday", window: "peak", startTime: "17:00", endTime: "01:00", pricePerHour: 850 },
  { id: "pr_pickle_weekend_all", sport: "pickleball", dayType: "weekend", window: "peak", startTime: "05:00", endTime: "01:00", pricePerHour: 950 },

  // Badminton
  { id: "pr_badminton_weekday_offpeak", sport: "badminton", dayType: "weekday", window: "offpeak", startTime: "05:00", endTime: "17:00", pricePerHour: 550 },
  { id: "pr_badminton_weekday_peak", sport: "badminton", dayType: "weekday", window: "peak", startTime: "17:00", endTime: "01:00", pricePerHour: 750 },
  { id: "pr_badminton_weekend_all", sport: "badminton", dayType: "weekend", window: "peak", startTime: "05:00", endTime: "01:00", pricePerHour: 850 },

  // Volleyball
  { id: "pr_vb_weekday_offpeak", sport: "volleyball", dayType: "weekday", window: "offpeak", startTime: "05:00", endTime: "17:00", pricePerHour: 900 },
  { id: "pr_vb_weekday_peak", sport: "volleyball", dayType: "weekday", window: "peak", startTime: "17:00", endTime: "01:00", pricePerHour: 1100 },
  { id: "pr_vb_weekend_all", sport: "volleyball", dayType: "weekend", window: "peak", startTime: "05:00", endTime: "01:00", pricePerHour: 1250 },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  { id: "cat_snacks", name: "Snacks & Quick Bites", order: 1, active: true },
  { id: "cat_beverages", name: "Energy & Beverages", order: 2, active: true },
  { id: "cat_meals", name: "High-Protein Meals", order: 3, active: true },
  { id: "cat_combos", name: "Matchday Combos", order: 4, active: true },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Snacks
  {
    id: "item_nachos",
    categoryId: "cat_snacks",
    name: "Pixel Loaded Corn Nachos",
    description: "Crispy tortilla chips topped with melted cheese sauce, salsa fresca, jalapenos, and sour cream.",
    price: 180,
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Bestseller", "Crunchy"],
    available: true,
    order: 1,
  },
  {
    id: "item_fries",
    categoryId: "cat_snacks",
    name: "Crispy Peri-Peri Fries",
    description: "Golden farm potato wedges dusted with spicy African bird's eye chili seasoning and served with garlic mayo.",
    price: 140,
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Spicy"],
    available: true,
    order: 2,
  },
  {
    id: "item_paneer_wrap",
    categoryId: "cat_snacks",
    name: "Charred Paneer Tikka Wrap",
    description: "Tandoori cottage cheese cubes rolled in whole wheat paratha with mint chutney and pickled onions.",
    price: 190,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Protein Pick"],
    available: true,
    order: 3,
  },
  {
    id: "item_chicken_wings",
    categoryId: "cat_snacks",
    name: "Smoky BBQ Chicken Wings",
    description: "6 crispy tender chicken wings glazed in signature smoky hickory barbecue glaze with sesame seeds.",
    price: 240,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=600&q=80",
    isVeg: false,
    badges: ["Non-Veg", "Juicy"],
    available: true,
    order: 4,
  },

  // Beverages
  {
    id: "item_electrolyte",
    categoryId: "cat_beverages",
    name: "Hydra-Electrolyte Citrus Burst",
    description: "Chilled isotonic citrus blend with potassium, magnesium, and Himalayan pink salt for rapid recovery.",
    price: 110,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Hydration", "Zero Sugar"],
    available: true,
    order: 1,
  },
  {
    id: "item_cold_brew",
    categoryId: "cat_beverages",
    name: "Nitro Cold Brew Coffee",
    description: "16-hour steeped single-origin Arabica cold brew with a creamy nitrogen foam head. Bold & unsweetened.",
    price: 160,
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["High Caffeine"],
    available: true,
    order: 2,
  },
  {
    id: "item_masala_chai",
    categoryId: "cat_beverages",
    name: "Arena Kadak Masala Chai",
    description: "Freshly brewed Assam tea leaves with crushed ginger, green cardamom, cloves, and whole milk.",
    price: 50,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Classic Hot"],
    available: true,
    order: 3,
  },
  {
    id: "item_berry_smoothie",
    categoryId: "cat_beverages",
    name: "Wild Berry Whey Smoothie",
    description: "Blueberries, strawberries, Greek yogurt, chia seeds, and 24g whey protein isolate. 100% natural.",
    price: 210,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["24g Protein"],
    available: true,
    order: 4,
  },

  // Meals
  {
    id: "item_chicken_bowl",
    categoryId: "cat_meals",
    name: "Grilled Chicken Athlete Bowl",
    description: "Herbed grilled chicken breast, quinoa pilaf, steamed broccoli, roasted bell peppers, and tahini drizzle.",
    price: 290,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    isVeg: false,
    badges: ["38g Protein", "Clean Fuel"],
    available: true,
    order: 1,
  },
  {
    id: "item_paneer_rice",
    categoryId: "cat_meals",
    name: "Power Paneer & Brown Rice Bowl",
    description: "Grilled garlic cottage cheese steak over spiced brown rice, edamame beans, and roasted sweet potato.",
    price: 260,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Veg Power", "High Fiber"],
    available: true,
    order: 2,
  },

  // Combos
  {
    id: "item_combo_champions",
    categoryId: "cat_combos",
    name: "The Champions Matchday Combo",
    description: "Charred Paneer Tikka Wrap + Peri-Peri Fries + Hydra-Electrolyte Citrus Burst drink.",
    price: 360,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    badges: ["Save ₹80", "Fan Favorite"],
    available: true,
    isCombo: true,
    comboItems: ["Paneer Wrap", "Peri-Peri Fries", "Electrolyte Drink"],
    savings: 80,
    order: 1,
  },
  {
    id: "item_combo_nonveg_duo",
    categoryId: "cat_combos",
    name: "Double Striker Non-Veg Combo",
    description: "Smoky BBQ Chicken Wings (6 pcs) + Grilled Chicken Bowl + Nitro Cold Brew.",
    price: 580,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80",
    isVeg: false,
    badges: ["Save ₹110", "High Protein"],
    available: true,
    isCombo: true,
    comboItems: ["BBQ Wings", "Chicken Athlete Bowl", "Cold Brew"],
    savings: 110,
    order: 2,
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: "tourn_ppl_2026",
    name: "Pixel Premier League (PPL) Box Cricket Championship",
    sport: "cricket",
    banner: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
    description: "The biggest box cricket showdown in the city! 16 competitive corporate and club teams battle under floodlights in an exciting 6-overs knockout tournament.",
    format: "Knockout",
    startDate: "2026-10-15",
    endDate: "2026-10-18",
    venue: "Main Cricket Turf, Pixel Arena",
    entryFee: 3500,
    prizePool: 50000,
    prizes: [
      { rank: "Winner", amount: 30000, trophy: "Grand Championship Trophy + Gold Medals" },
      { rank: "Runner-Up", amount: 15000, trophy: "Runner-Up Trophy + Silver Medals" },
      { rank: "Player of Tournament", amount: 5000, trophy: "Golden Bat Memento" },
    ],
    teamSizeMin: 6,
    teamSizeMax: 8,
    maxTeams: 16,
    registeredCount: 9,
    registrationDeadline: "2026-10-12",
    rules: [
      "Each match is 6 overs per side; maximum 2 overs per bowler.",
      "Direct hit on roof netting without bouncing is OUT.",
      "All matches played with professional Vicky heavy tennis balls provided by arena.",
      "Teams must report 20 minutes prior to their fixture schedule.",
      "Umpire's decision on no-balls and boundary calls is absolute and final.",
    ],
    faq: [
      { q: "Can we register without all 8 players finalized?", a: "Yes, you can register with captain details and minimum 6 players, and update substitutes before the deadline." },
      { q: "Are colored jerseys mandatory?", a: "Teams should preferably wear matching colors. Pixel Arena also provides color bibs on request." },
      { q: "What is the refund policy?", a: "Cancellations made 72 hours before the tournament start date are eligible for an 80% refund." },
    ],
    status: "UPCOMING",
  },
  {
    id: "tourn_pickle_open",
    name: "Smash & Dink Open Pickleball Doubles Cup",
    sport: "pickleball",
    banner: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80",
    description: "Fast-paced, non-stop dinking and smashing! Open gender doubles tournament played under USAPA guidelines on our cushion acrylic court.",
    format: "Round-Robin",
    startDate: "2026-10-08",
    endDate: "2026-10-09",
    venue: "Pro Court 1, Pixel Arena",
    entryFee: 1200,
    prizePool: 20000,
    prizes: [
      { rank: "1st Place Champions", amount: 12000, trophy: "Crystal Paddle Trophy" },
      { rank: "2nd Place Finalists", amount: 6000, trophy: "Silver Medals" },
      { rank: "3rd Place", amount: 2000, trophy: "Bronze Medals" },
    ],
    teamSizeMin: 2,
    teamSizeMax: 2,
    maxTeams: 16,
    registeredCount: 13,
    registrationDeadline: "2026-10-06",
    rules: [
      "Standard USAPA rally scoring to 11 points (win by 2).",
      "Two matches guaranteed in group stage before knockout qualifiers.",
      "Dura Fast 40 tournament approved balls will be used.",
      "Non-marking rubber-soled court shoes are mandatory.",
    ],
    faq: [
      { q: "Is this open to mixed doubles?", a: "Yes! Men's, women's, and mixed doubles all compete in the open bracket with seeded handicap." },
    ],
    status: "FILLING_FAST",
  },
  {
    id: "tourn_badminton_monsoon",
    name: "Monsoon Badminton Smashfest",
    sport: "badminton",
    banner: "https://images.unsplash.com/photo-1521537634581-0dced2fedc22?auto=format&fit=crop&w=1200&q=80",
    description: "Intense indoor singles & doubles championship held earlier this season with 32 elite players across the district.",
    format: "Knockout",
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    venue: "Indoor Court, Pixel Arena",
    entryFee: 800,
    prizePool: 25000,
    prizes: [
      { rank: "Winner", amount: 15000, trophy: "Gold Trophy" },
      { rank: "Runner-Up", amount: 10000, trophy: "Silver Trophy" },
    ],
    teamSizeMin: 1,
    teamSizeMax: 2,
    maxTeams: 16,
    registeredCount: 16,
    registrationDeadline: "2026-08-10",
    rules: [
      "BWF 21-point best of 3 sets format.",
      "Feather shuttlecocks (Yonex AS-30) provided for all rounds.",
    ],
    faq: [],
    status: "COMPLETED",
    winners: [
      { rank: "Champions", team: "Thunder Shuttlers (Rohan & Karthik)", prize: "₹15,000 + Golden Trophy" },
      { rank: "Runners-Up", team: "Smash Bros (Aditya & Sameer)", prize: "₹10,000 + Silver Plate" },
    ],
    results: [
      { match: "Finals: Thunder Shuttlers vs Smash Bros", score: "21-18, 19-21, 21-16", winner: "Thunder Shuttlers" },
      { match: "Semi 1: Thunder Shuttlers vs Net Masters", score: "21-14, 21-12", winner: "Thunder Shuttlers" },
      { match: "Semi 2: Smash Bros vs Ace Killers", score: "22-20, 21-17", winner: "Smash Bros" },
    ],
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  name: "Pixel Arena",
  tagline: "Premier Multi-Sport Turf Ground",
  city: "Mathura, Uttar Pradesh",
  address: "Near Pulse Fitness Gym, Mathura, Uttar Pradesh 281001",
  phone: "+91 98765 43210",
  whatsapp: "+919876543210",
  email: "bookings@pixelarena.in",
  mapEmbedUrl: "https://maps.google.com/maps?q=27.5040781,77.6564178&hl=en&z=17&output=embed",
  mapsUrl: "https://www.google.com/maps/place/Pulse+Fitness+Gym/@27.5040828,77.6538375,17z/data=!3m1!4b1!4m6!3m5!1s0x397371bf572f7a49:0xcd80515d0cf062ae!8m2!3d27.5040781!4d77.6564178",
  openTime: "05:00",
  closeTime: "01:00",
  bookingWindowDays: 14,
  maxSlotsPerBooking: 4,
  holdMinutes: 10,
  adminApprovalWindowHours: 2,
  socials: {
    instagram: "https://instagram.com/pixelarenaturf",
    facebook: "https://facebook.com/pixelarenaturf",
    twitter: "https://twitter.com/pixelarenain",
    youtube: "https://youtube.com/@pixelarena",
  },
  facilities: [
    {
      title: "FIFA-Grade Monofilament Turf",
      desc: "50mm high-density artificial turf with non-abrasive infill for maximum player safety and natural ball bounce.",
      icon: "Shield",
    },
    {
      title: "8x High-Lux LED Stadium Floodlights",
      desc: "Daylight illumination (500+ lux) with glare cutters designed for clear night matches and broadcast quality.",
      icon: "Zap",
    },
    {
      title: "Covered Spectator Seating",
      desc: "Tiered gallery seats for 100+ fans with clear viewing angles and mist fans during afternoon games.",
      icon: "Users",
    },
    {
      title: "Pixel Fuel Cafe",
      desc: "In-house sports cafe serving gourmet healthy meal bowls, artisanal cold brew, and fresh hydration drinks.",
      icon: "Coffee",
    },
    {
      title: "Locker Rooms & Hot Showers",
      desc: "Hygienic changing suites, keyless digital lockers, and high-pressure hot water showers.",
      icon: "Sparkles",
    },
    {
      title: "Dedicated Valet & Vehicle Parking",
      desc: "Ample covered parking space for 40+ cars and 80+ two-wheelers with 24/7 CCTV surveillance.",
      icon: "Car",
    },
  ],
  upiId: "pixelarena@upi",
  upiPayeeName: "PIXEL ARENA SPORTS LLP",
  useStaticQr: false,
  taxPercent: 5,
  policiesText: `Cancellation & Refund Policy:
1. Cancellations made more than 12 hours before slot time are eligible for 100% credit or rescheduling.
2. Cancellations made between 4 to 12 hours receive 50% refund.
3. Cancellations made under 4 hours are non-refundable.
4. In case of heavy rain/waterlogging, slots are automatically rescheduled at zero penalty.
5. All payments are verified manually via UPI transaction IDs (UTR). Please retain your payment screenshot.`,
  promoBanners: [
    {
      id: "promo_night_cricket",
      text: "⚡ MIDNIGHT CRICKET MADNESS: Flat 20% off on all slots after 11:00 PM on weekdays! Use UPI checkout.",
      link: "#book",
      active: true,
    },
    {
      id: "promo_pickleball",
      text: "🏓 Weekend Pickleball slots filling fast. Book your court now!",
      link: "#book",
      active: true,
    },
  ],
};

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: "admin_super_1",
    email: "admin@pixelarena.in",
    name: "Pixel Admin (Owner)",
    role: "superadmin",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "admin_staff_1",
    email: "staff@pixelarena.in",
    name: "Arena Manager",
    role: "staff",
    createdAt: "2026-02-15T00:00:00Z",
  },
];
